### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by jxv** [7drl-haskell/day1#3]
- [x] Start screen
  - [x] Name of the game?
  - [x] Enter/space
- [x] Rooms
  - [x] Bounded room, Wall: Black
  - [x] Many rooms
     - [x] 2 rooms
     - [x] 4 rooms
     - [x] X rooms
     - [x] Generate rooms
     - [x] Colors (0)
- [x] Doors
   - [x] Colors (2)
   - [x] Labeled with Number
- [x] Enemy
   - [x] Non-moving centered
   - [x] Damage value
   - [x] Damage sfx
   - [x] Color: Red1
- [x] Player
   - [x] Spawn point
   - [x] movable with arrows
   - ~walking sfx~
   - [x] health points
   - [x] Color: White1
   - [x] Sfx for changing rooms
   - [x] HUD for health points
- [x] End game
   - [x] Room count
   - [x] Death sfx
- [x] Collision detection

**Comment by jxv** [comment]
@rashadg1030 Use a `Data.Set` for wall indices and `Data.Map` for doors `Map (Int,Int) Int`. Those are easier to lookup for collision detection.

**Comment by rashadg1030** [comment]
@jxv Okay will do

**Comment by rashadg1030** [comment]
@jxv So instead of a list of wall locations it's gonna be a set? And instead of list of doors its gonna be a map? I think I get the idea

**Comment by rashadg1030** [comment]
@jxv and for enemies should it be Map (Int, Int) Enemy?

**Comment by rashadg1030** [comment]
@jxv I have an Enemy datatype defined as:

```
data Enemy = Enemy
  { enemyPos :: (Int, Int)
  , enemyRoom :: RoomIndex
  , enemyHp :: Int
  , enemyAtk :: Int
  } deriving (Show, Eq)
```

If we use map I guess we don't need an enemyPos.
